events/isc-spring-2016.md

Fix typo in isc-spring-2016.md

---

_data/navigation.yml
_includes/_sidebar.html

Add wiki to sidebar - fixes #27

---

pages/articles.md

This is my first attempt at learning how to make a pull request. I've started a page 'articles.md' with very little contents (only 2 lines) as a test. feedback welcome.

Start of a page "articles.md"

---

_data/navigation.yml

This puts About up in the navigation bar replacing Contact (forgot to do this in the first submission). Confirmed CC-BY-SA.

2016-06-13 forgot to update navigation.yml

---

pages/articles.md

Attempting to fix link format from @kjstol and added a quick explanation sentence at
the top

Migrating article list from inner-sourcing.com

---

pages/articles.md

After Nick Yeates++ converted up to 2005, this PR includes conversion of 2006-2015 links to wiki format.

Finish conversion of inner source links on the web

---

_data/navigation.yml
_includes/_sidebar.html
events/index.md
events/isc-fall-2016.md
events/isc-spring-2017.md
resources/articles.md
resources/index.md

Events and resources

---

pages/contribute.md

Hi @cewilliams,
here comes my first PR to InnerSourceCommons. ;-) I've fixed the broken link to your OSCON slides on the contribute page.
Cheers,
Robert

#64 fixed issue with link to OSCON slides in contribute.md

---

resources/articles.md

Public information about Inner Source from Bitergia's speakerdeck and blog

Added slides link and blog post about Inner Source 

---

pages/contribute.md

I fixed a very small typo in the first paragraph.

Small Typo Fix

---

resources/articles.md

Also fixed spacing issue, which didnt list 2016 articles in a list

Added article posted to Slack

---

pages/getting-started.md

Small change to allow travis to catch up.

Add image float

---

_data/navigation.yml
_includes/_sidebar.html
events/index.md

I edited _data/navigation.yml (to add a drop down event for the webinar), _includes/_sidebar.html (to add a mention of the webinar) and events/index.md (to add the webinar + change the formatting so that a little less vertical space is used -- using an unordered list instead of level 2 headers to separate events).

2017-05-15 added O'Reilly June 1st webinar on InnerSource Patterns

---

_includes/_sidebar.html
events/isc-fall-2017.md

Removed mention of Ignite class (no longer relevant), closed registration and added a restaurants list.

2017-09-20 closed registration

---

_data/navigation.yml

upcoming events -> events in menu

2017-09-29

---

_includes/_sidebar.html

I haven't tested it out yet, but seems safe enough?
Plus want to try out the web site editing during the session

Remove ISC Fall event (already happened)

---

_includes/_sidebar.html

2018-01-04 minor fix

---

events/isc-spring-2018.md
pages/fallsummit2018.md

Added a section on Food in the ISC S6 page; also created a short URL pointer to the ISC S7 event.

2018-02-21 changes

---

_includes/_sidebar.html
events/isc-fall-2018.md

Updating Fall 2018 Summit CFP dates

---

events/isc-spring-2018.md

Hey @NewMexicoKid . I've just added the registration link. I have also slightly rearranged the sections for the registration link to be more prominent. Thanks in advance for the review.

Registration link added

---

events/isc-spring-2018-agenda.md

Hey @NewMexicoKid . Yet another one. Maybe we should think about me getting merge rights as well, so you don't have to do all the merging chores. @cewilliams : would that be an option?

corrected grammar error

---

events/isc-spring-2018.md

Hey @NewMexicoKid . I've updated the travel information as discussed yesterday. Can you pls. check and see if they are indeed helpful and if yes, pls. merge this PR? Thanks in advance and cheers,
Georg

Updated travel information

---

events/isc-spring-2018.md

Fixed a typo in the events/isc-spring-2018.md

Fixed: posers -> posters

---

events/isc-spring-2018-speakers.md

Hi @NewMexicoKid and @cewilliams ,
here's an update for the ISC.S6 website. Thanks in advance for merging. Btw.: Is there any news on giving me merge privileges on this repo?
Cheers,
Georg

Updated bio of Rekha Joshi

---

events/isc-spring-2018.md

Added link to informal survey of travel schedules to help plan pre-/post-Summit activities.

2018-04-16

---

events/isc-spring-2018-agenda.md
events/isc-spring-2018-speakers.md

Hi @NewMexicoKid . I have to correct my correction. That's what you get when you're doing too many things at the same time, I guess. Sorry for the mess.

Corrected bio and abstract of Rekha Joshi ... again

---

events/isc-spring-2018-agenda.md

This PR fixes an error in the agenda (overlapping times)

Corrected error in agenda

---

events/isc-fall-2018.md

Added Registration Link to ISC Fall Summit page. Please publish!

Added Registration Link to ISC Fall Summit page

---

resources/articles.md

Missing blank line is messing up the itemization list

fixed markdown

---

_includes/_sidebar.html
pages/patterns.md

updated links to redirect to new patterns repo location

---

pages/learning-path.md

* Copied https://github.com/paypal/InnerSourceCommons/blob/master/pages/gdrive.md
* Not sure how to test.

innersourcecommons.org/learningpath redirect
